services:
  rpforlife-telepathy:
    build: ./server
    networks:
      - proxy
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.telepathy-web.rule=Host(`telepathy.unigames.asn.au`)"
      - "traefik.http.routers.telepathy-web.entrypoints=websecure"
      - "traefik.http.routers.telepathy-web.tls=true"
      - "traefik.http.routers.telepathy-web.tls.certresolver=le"
      # Port
      - "traefik.http.services.telepathy-web.loadbalancer.server.port=80"
    secrets:
      - roleplay-password

secrets:
  roleplay-password:
    file: secrets/password

networks:
  proxy:
    external: true
